### ISSUE TITLE
Issue with the watch option

### ISSUE THREAD

**Issue by kefniark** [hoperyy/sync-directory#2]
## Description
I noticed an issue while using this library.
The watcher works fine for most common file operation:
* creating file
* updating file
* moving or renaming file

## Usage
```ts
const sync = require('sync-directory');
sync(src, dst, {
        watch: true,
        cb: codeUpdated
});
```
But if I create a folder and delete it, the watcher dies.
```
Error: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:125:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Exit status 1
```

## Spec
* Windows 10 64 bits
* Node 12

**Comment by hoperyy** [comment]
@kefniark 

I noticed your issue. I didn't find this because I use Mac not windows.

I published a new version 2.0.9 to support a new api called `onError` callback function.

And I found some answers when operating files in windows: https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows
